CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    annotation         VARCHAR(1000)                           NOT NULL,
    description        VARCHAR(10000)                          NOT NULL,
    category_id        BIGINT,
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    location_lat       FLOAT,
    location_lon       FLOAT,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  INTEGER                                 NOT NULL,
    request_moderation BOOLEAN                                 NOT NULL,
    initiator_id       BIGINT,
    state              VARCHAR(255)                            NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT PK_EVENT PRIMARY KEY (id),
    CONSTRAINT FK_CATEGORY_ID_ON_EVENT FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT FK_USER_ID_ON_EVENT FOREIGN KEY (initiator_id) REFERENCES users (id)
);

INSERT INTO categories (id, name)
VALUES (0, 'NOT ASSIGNED')
ON CONFLICT DO NOTHING
;

CREATE TABLE IF NOT EXISTS requests
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id BIGINT,
    user_id  BIGINT,
    status   VARCHAR(255)                            NOT NULL,
    CONSTRAINT PK_REQUESTS PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_ID_ON_REQUEST FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_USER_ID_ON_REQUEST FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    title  VARCHAR(255)                            NOT NULL,
    CONSTRAINT PK_COMPILATIONS PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    event_id       BIGINT,
    compilation_id BIGINT,
    CONSTRAINT PK_EVENTS_COMPILATIONS PRIMARY KEY (event_id, compilation_id),
    CONSTRAINT FK_EVENTS FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_COMPILATIONS FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text               VARCHAR(512)                            NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id           BIGINT,
    user_id            BIGINT,
    edited             BOOLEAN                                 NOT NULL,
    CONSTRAINT PK_COMMENT PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_ID_ON_COMMENT FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_USER_ID_ON_COMMENT FOREIGN KEY (user_id) REFERENCES users (id)
    );

INSERT INTO users
VALUES
(1,Kyle Schiller,Emiliano11@gmail.com),
(2,Marcia Lueilwitz,Addison.Douglas32@gmail.com),
(3,Donnie Grimes Jr.,Julia.Walker@hotmail.com),
(4,Dean Hand,Zoila67@yahoo.com),
(5,Rosa Doyle I,Ramon53@hotmail.com),
(6,Homer Zboncak,Donna.Koelpin@yahoo.com),
(7,Mrs. Minnie Bernhard,Willa58@yahoo.com),
(8,Peggy Douglas,Krista_Schinner35@gmail.com),
(9,Dana Deckow,Raleigh33@hotmail.com),
(10,Joe Cartwright,Fletcher.Morar10@gmail.com)
ON CONFLICT DO NOTHING
;

INSERT INTO events
VALUES
(1,Quis dolorem voluptas illum magnam voluptatibus.,Sit delectus quo. Ullam temporibus cum maxime distinctio eum. Distinctio est natus itaque dolor deleniti quam iure tempore.,"Non accusamus fugiat veritatis. Corporis quam omnis beatae qui quisquam voluptatem provident officia et. Sapiente et nihil delectus ullam fuga itaque et nulla dolorem.
Quidem officiis qui est. Eaque consequuntur et facilis et saepe in vel deserunt quia. Harum dolor labore veritatis esse enim nostrum est unde dolores. Id nemo ut sit qui. Iusto eos commodi eius. Et quaerat ducimus eos perspiciatis voluptatem.
Facilis eos necessitatibus at corrupti est repellat. Ut qui provident consequatur. Tempora perspiciatis non vel voluptate fugit neque quasi dolorem. Enim facere corporis error at quam aut. Officiis et debitis in molestias nesciunt. Quas quis quae rerum natus.",1,2022-12-31 07:33:02.000000,2.5483,-48.6144,true,358,false,1,PUBLISHED,2022-12-31 02:33:02.623393,2022-12-31 02:33:02.623393),
(2,Totam et officiis consequatur voluptatem.,Et odio enim quo ratione consequuntur error quia. Ut qui et fugiat omnis non optio sit. Repellat iste et et inventore laudantium ab dolores aut et.,"Non et commodi minus. Consequatur recusandae nesciunt cum optio et id. Eligendi sint fugiat perspiciatis quas quia iste eius. Quas accusamus officia et quas eius nam a nisi quae.
Corrupti architecto quo veniam rem porro distinctio. Veritatis velit voluptatem aperiam. Nulla voluptatem facere facilis sunt reiciendis.
Quis eum sed in expedita vero. Accusantium necessitatibus sed ad. Enim mollitia omnis quibusdam omnis.",2,2022-12-31 07:44:22.000000,-84.2799,-157.5753,false,166,false,2,PUBLISHED,2022-12-31 02:44:22.106317,2022-12-31 02:44:22.106317),
(3,Quia enim commodi quas alias ratione et.,Reprehenderit mollitia possimus fugiat voluptas eos qui facere et. Non in dolorem et asperiores id quisquam vitae. Dolore corporis ea magni sint non. Veritatis quis non. Aliquam ratione quos eos exercitationem illo labore dolores. Aliquam tenetur id dolor reprehenderit libero.,"Dolorum in quos. A esse id laudantium itaque. Consequatur quis et quibusdam et reprehenderit laboriosam repellendus molestias.
Mollitia amet et alias omnis sit minus incidunt sed adipisci. Dolor aliquam numquam tempore. Quo facilis velit. Consequatur molestias voluptas cumque architecto qui.
Soluta dolores vel minus mollitia. Maiores non eaque et dolorem dolores accusamus. Fugit occaecati ab quo odit sit maxime est quasi autem.",3,2022-12-31 07:44:36.000000,9.9534,-108.8203,true,663,true,5,PUBLISHED,2022-12-31 02:44:36.141697,2022-12-31 02:44:36.141697),
(4,Voluptatem odit ut et est iste et ad et.,Inventore voluptate qui. Neque et magnam harum quod. Voluptatum autem ut dolor dolor id omnis dolorem laboriosam. Recusandae quis impedit delectus quia quos nulla ea. Quod consequatur praesentium beatae fugiat. Architecto ab aut occaecati voluptatum quis deserunt eum ut.,"Aut laborum et illo quia aspernatur iure enim facilis. Perferendis unde voluptatem quod illum eveniet. Vero et placeat suscipit. Molestiae qui consequatur voluptas id quia non. Consequuntur quidem ut sint. Iusto ipsum quas pariatur saepe enim id exercitationem.
Voluptas incidunt nihil itaque. Ratione fuga necessitatibus. Incidunt autem ab quia dolor.
Distinctio sapiente officia. Ut corrupti eveniet quaerat. Consequuntur odit qui sequi saepe et excepturi et repellendus quaerat. Ut voluptate est.",4,2022-12-31 07:44:36.000000,-66.8935,92.1266,true,227,true,6,PENDING,2022-12-31 02:44:36.452073,2022-12-31 02:44:36.452073),
(5,Perferendis unde aspernatur harum ducimus eum quas modi facere.,Cumque expedita quidem eum voluptatem natus voluptas. Non beatae quae quae rerum itaque qui necessitatibus at non. Nam eos fuga debitis omnis rerum eum aspernatur modi eos.,"Earum numquam consequatur voluptatem rerum. Illum deserunt voluptas consequatur. Saepe ea totam saepe id et officia labore. Eum ut suscipit architecto magnam vitae distinctio in enim.
Labore soluta est. Ipsa fugiat et necessitatibus dignissimos natus omnis qui. Atque doloremque earum.
Similique eligendi est voluptas deleniti minus. Velit perferendis illum optio suscipit voluptatum nobis. Ut dolore esse. Sequi deleniti soluta ea est quidem sunt quia est vel.",6,2022-12-31 07:44:37.000000,33.075,174.6842,false,183,false,8,PUBLISHED,2022-12-31 02:44:37.112169,2022-12-31 02:44:37.112169),
(6,Autem ut fugiat ad quas quia nostrum tempora est aut.,Sint fugit similique velit tempora quod itaque autem cumque consequatur. Et possimus est quia autem provident quos sequi quam esse. Impedit id quibusdam ullam reiciendis quia accusamus hic.,"Commodi nemo explicabo ad molestias veniam illum quod iure voluptate. Rerum corrupti omnis debitis. Laboriosam incidunt commodi aperiam fugiat voluptas itaque.
Qui sit dicta distinctio aut in est reiciendis dolor doloremque. A quae dolor sunt quibusdam atque. Deleniti et voluptatem nobis. Vero nisi reprehenderit saepe fuga aut quam. Necessitatibus eum eum consequatur aut non.
Perferendis quia facilis libero eveniet. Consequatur reprehenderit sunt atque. Pariatur minima ratione sint aliquid reprehenderit voluptatem recusandae. Asperiores vel alias delectus omnis voluptatem quam. Officia voluptas accusantium saepe et possimus eaque. Velit architecto quisquam nihil quae consequuntur repellendus aliquid.",8,2022-12-31 07:44:37.000000,47.5416,-47.2834,false,936,false,9,PENDING,2022-12-31 02:44:37.787314,2022-12-31 02:44:37.787314),
(7,Dicta qui necessitatibus possimus ipsum sint repellat.,Impedit omnis ab sit assumenda. Ipsa animi possimus. Sit voluptatem qui quis itaque. Odio maxime fuga. Minus eligendi consequuntur ea.,"Debitis ullam rerum ut minus inventore ipsa quos et velit. Numquam excepturi sit et aliquam nulla eos dolor. Aut expedita quia aliquid atque tenetur.
Rerum perferendis consectetur est ut natus nulla perferendis fugiat. Modi commodi rerum. Nisi aut eveniet et.
Enim provident minus neque adipisci explicabo natus. Tenetur nobis ut dolorum voluptas ipsam eos. Et dolorum inventore error enim omnis voluptas. Doloribus et dolorem mollitia in quaerat consequatur. Ut ea nisi nihil voluptas suscipit ut id. Mollitia atque nihil velit consequatur vel alias voluptatem.",19,2022-12-31 07:44:40.000000,-75.9909,151.736,true,68,false,16,PENDING,2022-12-31 02:44:40.835365,2022-12-31 02:44:40.835365),
(8,Consectetur voluptas reiciendis praesentium voluptatem et consectetur.,Dolores quisquam debitis est ut accusamus est cum in amet. Sed temporibus deserunt. Laudantium ex voluptatum aut dolorem eligendi eos voluptate iste. Commodi corporis quia quis fugiat minus. Aut commodi dolor dolorem ut velit. Dolorum natus doloribus maiores omnis maxime nihil eligendi explicabo et.,"Consectetur quidem nam ut. Enim in quis aut vero sit et. Pariatur fugiat ad enim ad officia quaerat id impedit beatae. Possimus in voluptas ducimus. Dicta nemo voluptatem sint at.
Aperiam pariatur labore quia amet aut placeat. At aut et consectetur sit quibusdam consequuntur ipsam. Et quo maiores est consequatur. Blanditiis deleniti illo corrupti. Beatae quia est voluptate aperiam.
Ea eius excepturi et rerum velit autem eius quia. Distinctio cumque provident blanditiis est. Dicta nobis esse dolores ut rerum id laborum.",20,2022-12-31 07:44:41.000000,-86.3383,-35.9704,false,837,true,17,PUBLISHED,2022-12-31 02:44:41.054122,2022-12-31 02:44:41.054122),
(9,Aliquam id rerum ut voluptatum dignissimos explicabo veritatis.,Quia sit est ut nemo maxime nam. Consequatur quam quia assumenda inventore. Voluptatem omnis harum aut ex id provident maiores fugiat. Est maxime totam praesentium. Sed non qui nam omnis id ut maiores libero. Accusantium rem vero esse.,"Aliquam odit omnis corporis aut consectetur ut rem sed et. Deleniti reiciendis id rerum eveniet nostrum mollitia laborum omnis. Ut consequuntur temporibus.
Quibusdam dicta sit. Error enim eum minima. Tenetur aut hic error. Quibusdam adipisci officia iste.
Quia maiores corrupti voluptas. Ut quis soluta sed ipsum aut. Earum nisi voluptas fuga laborum. Minus sit et esse ipsum est omnis excepturi est et.",21,2022-12-31 07:44:41.000000,13.4037,-57.7476,false,260,false,19,PUBLISHED,2022-12-31 02:44:41.371502,2022-12-31 02:44:41.371502),
(10,Totam ut veniam iure corrupti ullam corrupti et quia autem.,Voluptas consequuntur quia non debitis amet sit pariatur quia rem. Et eos eum dolore provident quod. Eum est accusantium nihil.,"Quas animi et consequatur accusamus sint. Eos quae et. Sed beatae quia qui ut quae et.
Quae eveniet nisi ut atque voluptatem. At non beatae saepe corrupti voluptatem quae facilis debitis. Est dolor amet quia cum accusamus excepturi ut praesentium.
Et natus consectetur. Sint ducimus dicta. Quasi ad id iure ducimus amet praesentium.",22,2022-12-31 07:44:41.000000,-52.6546,88.6798,true,685,true,20,PENDING,2022-12-31 02:44:41.653504,2022-12-31 02:44:41.653504)
ON CONFLICT DO NOTHING
;