CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    annotation         VARCHAR(1000)                           NOT NULL,
    description        VARCHAR(10000)                          NOT NULL,
    category_id        BIGINT,
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    location_lat       FLOAT,
    location_lon       FLOAT,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  INTEGER                                 NOT NULL,
    request_moderation BOOLEAN                                 NOT NULL,
    initiator_id       BIGINT,
    state              VARCHAR(255)                            NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT PK_EVENT PRIMARY KEY (id),
    CONSTRAINT FK_CATEGORY_ID_ON_EVENT FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT FK_USER_ID_ON_EVENT FOREIGN KEY (initiator_id) REFERENCES users (id)
);

INSERT INTO categories (id, name)
VALUES (0, 'NOT ASSIGNED')
ON CONFLICT DO NOTHING
;

CREATE TABLE IF NOT EXISTS requests
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id BIGINT,
    user_id  BIGINT,
    status   VARCHAR(255)                            NOT NULL,
    CONSTRAINT PK_REQUESTS PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_ID_ON_REQUEST FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_USER_ID_ON_REQUEST FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    title  VARCHAR(255)                            NOT NULL,
    CONSTRAINT PK_COMPILATIONS PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    event_id       BIGINT,
    compilation_id BIGINT,
    CONSTRAINT PK_EVENTS_COMPILATIONS PRIMARY KEY (event_id, compilation_id),
    CONSTRAINT FK_EVENTS FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_COMPILATIONS FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text               VARCHAR(512)                            NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id           BIGINT,
    user_id            BIGINT,
    edited             BOOLEAN                                 NOT NULL,
    CONSTRAINT PK_COMMENT PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_ID_ON_COMMENT FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_USER_ID_ON_COMMENT FOREIGN KEY (user_id) REFERENCES users (id)
    );

INSERT INTO users
VALUES
(1,'Kyle Schiller','Emiliano11@gmail.com'),
(2,'Marcia Lueilwitz','Addison.Douglas32@gmail.com'),
(3,'Donnie Grimes Jr.','Julia.Walker@hotmail.com'),
(4,'Dean Hand','Zoila67@yahoo.com'),
(5,'Rosa Doyle I','Ramon53@hotmail.com'),
(6,'Homer Zboncak','Donna.Koelpin@yahoo.com'),
(7,'Mrs. Minnie Bernhard','Willa58@yahoo.com'),
(8,'Peggy Douglas','Krista_Schinner35@gmail.com'),
(9,'Dana Deckow','Raleigh33@hotmail.com'),
(10,'Joe Cartwright','Fletcher.Morar10@gmail.com')
ON CONFLICT DO NOTHING;

INSERT INTO categories
VALUES
(1,'holistic88'),
(2,'Liaison64'),
(3,'benchmark35'),
(4,'emulation78'),
(6,'Home19'),
(7,'lavender17'),
(8,'frictionless21'),
(9,'mesh18')
ON CONFLICT DO NOTHING;

INSERT INTO events
VALUES
    (1,'Quis dolorem voluptas illum magnam voluptatibus.','Sit delectus quo. Ullam temporibus cum maxime distinctio eum. Distinctio est natus itaque dolor deleniti quam iure tempore.','"Non accusamus fugiat veritatis. Corporis quam omnis beatae qui quisquam voluptatem provident officia et. Sapiente et nihil delectus ullam fuga itaque et nulla dolorem.
Quidem officiis qui est. Eaque consequuntur et facilis et saepe in vel deserunt quia. Harum dolor labore veritatis esse enim nostrum est unde dolores. Id nemo ut sit qui. Iusto eos commodi eius. Et quaerat ducimus eos perspiciatis voluptatem.
Facilis eos necessitatibus at corrupti est repellat. Ut qui provident consequatur. Tempora perspiciatis non vel voluptate fugit neque quasi dolorem. Enim facere corporis error at quam aut. Officiis et debitis in molestias nesciunt. Quas quis quae rerum natus."',1,'2022-12-31',-48.6144,-63.6144, true,358,false,1,'PUBLISHED','2022-12-31','2022-12-31'),
    (2,'Totam et officiis consequatur voluptatem.','Et odio enim quo ratione consequuntur error quia. Ut qui et fugiat omnis non optio sit. Repellat iste et et inventore laudantium ab dolores aut et.','"Non et commodi minus. Consequatur recusandae nesciunt cum optio et id. Eligendi sint fugiat perspiciatis quas quia iste eius. Quas accusamus officia et quas eius nam a nisi quae.
Corrupti architecto quo veniam rem porro distinctio. Veritatis velit voluptatem aperiam. Nulla voluptatem facere facilis sunt reiciendis.
Quis eum sed in expedita vero. Accusantium necessitatibus sed ad. Enim mollitia omnis quibusdam omnis."',2,'2022-12-31',-84.2799,-157.5753,false,166,false,2,'PUBLISHED','2022-12-31','2022-12-31'),
    (3,'Quia enim commodi quas alias ratione et.','Reprehenderit mollitia possimus fugiat voluptas eos qui facere et. Non in dolorem et asperiores id quisquam vitae. Dolore corporis ea magni sint non. Veritatis quis non. Aliquam ratione quos eos exercitationem illo labore dolores. Aliquam tenetur id dolor reprehenderit libero.','"Dolorum in quos. A esse id laudantium itaque. Consequatur quis et quibusdam et reprehenderit laboriosam repellendus molestias.
Mollitia amet et alias omnis sit minus incidunt sed adipisci. Dolor aliquam numquam tempore. Quo facilis velit. Consequatur molestias voluptas cumque architecto qui.
Soluta dolores vel minus mollitia. Maiores non eaque et dolorem dolores accusamus. Fugit occaecati ab quo odit sit maxime est quasi autem."',3,'2022-12-31',9.9534,-108.8203,true,663,true,5,'PUBLISHED','2022-12-31','2022-12-31')

ON CONFLICT DO NOTHING;